### ISSUE TITLE
How to use generated parameters

### ISSUE THREAD

**Issue by athkalia** [Nicologies/PrExtras#1]
Hello,

I am wondering how I can use the generated parameters, for example 
teamcity.build.pull_req.author in other build steps.

I tried %teamcity.build.pull_req.author% and it doesn't seem to work.

Thanks in advance,
Sakis

**Comment by EbenZhang** [comment]
You have to define the `teamcity.build.pull_req.author` in your build configuration's parameters tab with empty value (will be filled at run-time) and then reference it from other steps.

if you have multiple projects, you can define it at the upper level, e.g. `<Root project>`

**Comment by athkalia** [comment]
Hello,

thanks for the reply.
That's one of the things I tried. Specifically I added everything as a parameter, made a build step that just prints all the properties in the logs:

echo assignee %teamcity.build.pull_req.assignee%
echo assignee email %teamcity.build.pull_req.assignee_email%
echo author %teamcity.build.pull_req.author%
echo author email %teamcity.build.pull_req.author_email%
echo branch name %teamcity.build.pull_req.branch_name%
echo closed %teamcity.build.pull_req.is_closed%
echo merged %teamcity.build.pull_req.is_merged%
echo is Pr %teamcity.build.pull_req.is_pull_req%
echo labels %teamcity.build.pull_req.labels%
echo participants %teamcity.build.pull_req.participants%
echo req url %teamcity.build.pull_req.url%



For the merge PR branch I got:
[08:15:01]Step 10/10: Command Line
[08:15:01][Step 10/10] Starting: C:\TeamCity\buildAgent\temp\agentTmp\custom_script5673404135763145613.cmd
[08:15:01][Step 10/10] in directory: C:\TeamCity\buildAgent\work\5173288095aa8636
[08:15:01][Step 10/10] assignee 
[08:15:01][Step 10/10] assignee email 
[08:15:01][Step 10/10] author 
[08:15:01][Step 10/10] author email 
[08:15:01][Step 10/10] branch name refs/pull/19/merge
[08:15:01][Step 10/10] closed false
[08:15:01][Step 10/10] merged false
[08:15:01][Step 10/10] is Pr false
[08:15:01][Step 10/10] labels 
[08:15:01][Step 10/10] participants 
[08:15:01][Step 10/10] req url 
[08:15:01][Step 10/10] Process exited with code 0

And for the head PR branch I got:

[08:14:50]Step 10/10: Command Line
[08:14:50][Step 10/10] Starting: C:\TeamCity\buildAgent\temp\agentTmp\custom_script759967048157133812.cmd
[08:14:50][Step 10/10] in directory: C:\TeamCity\buildAgent\work\5173288095aa8636
[08:14:50][Step 10/10] assignee 
[08:14:50][Step 10/10] assignee email 
[08:14:50][Step 10/10] author 
[08:14:50][Step 10/10] author email 
[08:14:50][Step 10/10] branch name refs/pull/19/head
[08:14:50][Step 10/10] closed false
[08:14:50][Step 10/10] merged false
[08:14:50][Step 10/10] is Pr false
[08:14:50][Step 10/10] labels 
[08:14:50][Step 10/10] participants 
[08:14:50][Step 10/10] req url 
[08:14:50][Step 10/10] Process exited with code 0


It seems like some values are not populated at all. Any idea on why that is?
It is a public github repo that I am connecting to, so on the "PullRequest Extra Info" build step I have selected "Github Account" and I left the fields empty. Then "Append the branch name to the build num label" is not ticked and "Fail the build if the pull request has conflicts" is.

Teamcity version is 10.0.4



Thanks again,
Sakis

**Comment by EbenZhang** [comment]
can you search the `teamcity.build.pull_req.author` in the parameters tab of a build to see if the parameter was filled with actual value? and also check the build log of the `prextras` build step to see if any errors?

I've also noticed you are accessing variables from a `cmd` file. As far as I know, only `env` parameters (e.g. `env.JAVA_HOME`)  are visible to batch file directly. You could pass `%teamcity.build.pull_req.author%`  as a parameter to the batch file or maybe, not sure,  create an `env.pull_req_author` with value of `%teamcity.build.pull_req.author%` and use `pull_req_author` in the batch file.

**Comment by athkalia** [comment]
Hey pal,

didn't actually notice that there was a parameters tab, that would have been easier to debug.
So not all of them get populated:

teamcity.build.pull_req.assignee	<empty>
teamcity.build.pull_req.assignee_email	<empty>
teamcity.build.pull_req.author	<empty>
teamcity.build.pull_req.author_email	<empty>
teamcity.build.pull_req.branch_name	refs/pull/19/head  
teamcity.build.pull_req.is_closed	false  
teamcity.build.pull_req.is_merged	false  
teamcity.build.pull_req.is_pull_req	false  
teamcity.build.pull_req.labels	<empty>
teamcity.build.pull_req.participants	<empty>
teamcity.build.pull_req.url	<empty>

**Comment by EbenZhang** [comment]
can you share your branch configuration in vcs root? I'm using `+:refs/pull/*/merge`

**Comment by athkalia** [comment]
in vcs root it's 
+:*
inside the build trigger the branch filter is 
-:*
+:refs/pull/*/merge
+:refs/pull/*/head

**Comment by EbenZhang** [comment]
The `+:*` will include everything thus `+:refs/pull/*/merge` has no effect.

Try change the default branch to `refs/heads/master`, and inside the build trigger change the branch filter to `+:refs/pull/*/merge`. You just need either `+:refs/pull/*/merge` or `+:refs/pull/*/head` where `head` is the branch itself while `merge` will be a merge commit of the branch and the branch it's targeting.

**Comment by athkalia** [comment]
Hey there,

this is on purpose. The default branch for me is develop, and then the branch specification on VCS root is +:* to include everything (as this VCS root is used by multiple build configuration, not only the Pull request build configuration. Then in the build trigger I say: "you know what, ignore all the branches that I mentioned earlier ( -:* ) but only check for the PR head and PR merge for this build config (+:refs/pull//merge, +:refs/pull//head) . Does this make any sense?

But you are right, I only need the merge branch really, not the head one. I'll try to see if that makes a difference

**Comment by EbenZhang** [comment]
just create a new release: https://github.com/Nicologies/PrExtras/releases/download/1.0.7/prextras.zip
can you test?

**Comment by athkalia** [comment]
Hello, same behavior unfortunately.
If I change my VCS roots to check for the refs/heads/develop, and as branch specification to check for PR merges ( +:refs/pull/*/merge ) and then in the build trigger I don't put any branch filter then it works properly. I think I'll just split my VCS roots, from having one to having multiple so that I can deal with this

**Comment by EbenZhang** [comment]
Assuming problem solved. Feel free to reopen.
