### ISSUE TITLE
Get only ID 

### ISSUE THREAD

**Issue by datasmurfen** [Nicologies/PrExtras#6]
Possible to only get the pull request ID, and not the URL ?

**Comment by EbenZhang** [comment]
you sgould be able to get it from teamcity already. cant remember extactly which one, you can try find it in a finished build's parameters.

**Comment by EbenZhang** [comment]
Exported as `teamcity.build.pull_req.number`. See https://github.com/Nicologies/PrExtras/releases/tag/1.0.13
